### ISSUE TITLE
Samenwerking

### ISSUE THREAD

**Issue by ghost** [tkon99/API-gepro-osi#2]
Hallo Thomas, 
Ik ben bezig met een IOS design. Zou je willen helpen met de recreation van Magister.
Vooral het PHP gedeelte want ik kan het design.
- Juul

**Comment by tkon99** [comment]
Ja hoor, je hebt eindelijk de goede repo gevonden :wink: 
Wat is je idee?

**Comment by ghost** [comment]
Ja het duurde even... Vanavond typ ik het idee zit nu op school. :) :+1:

**Comment by ghost** [comment]
Nou, Hier ben ik dan.
Mijn idee was een betere magister. het lijk op SimplyHomework maar dit is echt puur op magister gericht.  Ik ben een WebDesigner en kan een beetje PHP en Javascript/JQuery.
-  Veel customisatie options (Denk aan achtergronden/layout) die per User in een database worden opgeslagen.
-  School wordt (Encrypted) iogeslagen in een Database (MySql of PDO denk ik.)
-  Extra features bijv. Meer opties om huiswerk af te vinken, Berekenen wat je het volgende SO/PW moet halen als je een Voldoende of een specefiek cijfer wilt staan gemiddeld.
-  En nog veel meer!

Mvg,
Juul

**Comment by tkon99** [comment]
Hi Juul,

Ik zal maar meteen eerlijk tegen je zijn: ik zie niet in hoe je dat gaat bereiken.
Lees dit niet verkeerd, ik was zelf 2 jaar geleden ook zo maar wat je wilt is echt niet haalbaar.
Als je een "beetje" php en javascript kan, ga je het niet redden om zo'n grote applicatie te bouwen. 
Bovendien doet simplyHomework precies hetzelfde (en meer) en daar zit al meer dan een jaar development in (12.388 regels code) dus het spreekt voor zich dat ik je in ieder geval er niet mee ga helpen om hetzelfde te doen.

Dat was genoeg negatief gedoe, nu een positievere insteek.
Toen ik jouw leeftijd had heb ik [Norbertaan](http://norbertaan.nl/) gebouwd, een website die het rooster van gepro-osi gebruikt en je rooster voor je onthoudt etc. Ik denk dat je hier een groot deel van je ideeën wel in kwijt zou kunnen. Zo zou je gebruikers achtergronden kunnen laten instellen en roosters van anderen kunnen laten bookmarken.

Daarvoor is deze library, die is makkelijk in gebruik en neemt alle moeilijke "parsing" weg die nodig is om het rooster om te zetten in data.

Natuurlijk is dit allemaal advies, het is aan jou wat je ermee doet.
Volg het op of bewijs me ongelijk. In ieder geval veel succes.

P.S. Mocht je hulp nodig hebben met een idee als Norbertaan dan kan ik altijd even voor je kijken natuurlijk. Ik ga het alleen niet voor je bouwen.

Met vriendelijke groet,

Thomas Konings

**Comment by ghost** [comment]
Oke duidelijk, Ik zal wat gaan proberen met jou library.
