### ISSUE TITLE
Klasrooster ophalen

### ISSUE THREAD

**Issue by KFC4Life** [tkon99/API-gepro-osi#3]
Hallo,

Ik heb een vraagje.
Hoe vraag ik een klas rooster op?

Het lukt me namelijk niet.

Misschien kan je een php example neergooien hier?

Klas: D2b
School: 1835

Met vriendelijke groet,
Siemen

**Comment by tkon99** [comment]
Hi,

Het zit hem in het volgende: jouw school heeft 11 uren ipv de 10 waarop de api is gebouwd. Echter heb ik er wel een functie inzitten die hem flexibel maakt (maar die is nooit getest).
Ik ga zo even voor je kijken.

Groeten,

Thomas

**Comment by tkon99** [comment]
Ok,
Een deel van de curl commands deed het niet meer omdat Schoolmaster de urls laatst heeft aangepast, dat is nu gefixt in de laatste versie (even opnieuw downloaden dus).

Dan werkt het volgende:
```PHP
<?php
include("rooster.class.php");
$rooster = new rooster(1835, 11);

$yoururl = $rooster->getUrl('klas', "D2b");
echo "Url: ".$yoururl."<br><hr>";

echo json_encode($rooster->getSchedule($yoururl));
?>
```

**Comment by KFC4Life** [comment]
Hallo,

Heel erg bedankt voor de fix, die urls vielen we net pas op.
Heb het pakketje even opnieuw gedownload en het werkt perfect.

Nogmaals bedankt.
