### ISSUE TITLE
Manier om tabbladen te detecteren

### ISSUE THREAD

**Issue by KFC4Life** [tkon99/API-gepro-osi#4]
Hallo,

Is er ook een manier aanwezig hoe ik kan controleren hoeveel roosterwijzigingen er zijn voor een specifieke groep?

EDIT:

Ik bedoel dus hoeveel er van dit soort tabjes zijn in magister:
https://i.imgur.com/kQ5BB7q.png

Ik weet niet of het normaal is maar op mijn school hebben we af en toe 1 of 2 tabjes erin staan dus dan wil ik die natuurlijk graag in mijn eigen systeem planten.

En dan natuurlijk alleen de gene die betrekking hebben tot de geselecteerde groep.

Groet,
Siemen

**Comment by tkon99** [comment]
Hi Siemen,

Dit kan niet met de PHP library, wel met die in Javascript (die is ook een stuk nieuwer).
Zie: https://github.com/tkon99/gepro-osi-JS

Eventueel kun je dit wel eenvoudig zelf realiseren (kijk dan even naar de code van de JS versie).
Ik ben sinds kort zelf gestopt met mijn rooster website, de code daarvan is hier beschikbaar (client):
https://github.com/tkon99/norbertaan
Allicht dat je daar (in de toekomst) wat aan hebt.

Ik weet niet precies wat je aan het bouwen bent en waar je heen wilt, ik ga niet stuk voor stuk dit soort dingen voor je oplossen.

Met vriendelijke groet,

Thomas

**Comment by tkon99** [comment]
Closing for now.

**Comment by KFC4Life** [comment]
Hallo Thomas,

Ik ben begonnen met het bouwen van mijn eigen rooster website (Speciaal gericht op m'n eigen klas en dan uitbreiden dat ik push notificatie krijg bij een roosterwijziging etc etc)
Maar ik begrijp uit je reactie dat je niet heel actief meer bezig bent met deze repo dus ik zal geen verdere issues meer aanmaken

En terugkomend op de JS repo, ik code alleen in PHP en heel weinig in JS (snap daar weinig van).
Desondanks je me niet verder kunt helpen toch nog heel erg bedankt! :)

P.S. de linkjes in je JS repo staan nog niet goed, wellicht een idee om die goed te zetten haha.

Met vriendelijke groet,
Siemen

**Comment by tkon99** [comment]
Hi Siemen,

Leuk dat je ook een rooster website gaat bouwen!
Met de PHP library zou dat moeten kunnen al heb ik PHP nooit echt geschikt gevonden voor real-time dingen zoals notificaties.
Ik heb Norbertaan altijd graag bijgehouden maar ben er nu mee gestopt omdat ik nu examen doe (en dus volgend jaar er niets meer aan heb.)

Met vriendelijke groet,

Thomas

**Comment by KFC4Life** [comment]
Hallo Thomas,

Het lukt al aardig maar loop vooral tegen problemen aan zoals dingetjes in de urls van magister.
Bij meer dan 2 wijzigingen gebruiken ze niet "wijzigingen=1" bijv maar "tabblad=1" etc.

Staat dat Norbertaan ook ergens in een repo? (Het hele pakket)

Met vriendelijke groet,

Siemen

**Comment by tkon99** [comment]
Hi Siemen,

Het hele pakket is niet openbaar beschikbaar omdat in die API en crawlers heel veel werk zit.
Ze zijn wel te koop voor een paar tientjes.

Met vriendelijke groet,

Thomas Konings
